baseURL = 'http://blog.jayjanssen.net/'
languageCode = 'en-us'
title = "Jay Janssen's MySQL and Infrastructure"
# author = 'Jay Janssen'
description = "MySQL and Infrastructure"
permalinks.posts = "posts/:year/:month/:title"

theme = "LoveIt"
# Theme settings: https://github.com/dillonzq/LoveIt/blob/master/config.toml

[author]
  name = 'Jay Janssen'

[params]
title = "Jay Janssen's MySQL and Infrastructure"
description = "MySQL and Infrastructure"

[params.app]
title = "Jay Janssen's MySQL and Infrastructure"
description = "MySQL and Infrastructure"

[params.header.title]
name = "blog.jayjanssen.net"
description = "MySQL and Infrastructure"

[params.home.profile]
subtitle = "Jay Janssen's MySQL and Infrastructure"
gravatarEmail = "jay.janssen@gmail.com"
typeit = true
social = true

[params.social]
Github = "jayjanssen"
Linkedin = "jayjanssen"
Twitter = "jayjanssen"

[outputs]
# Adding JSON here allows search to work
home = ["HTML", "RSS", "JSON"]

[params.search]
enable = true
type = "lunr"
highlightTag = "em"
contentLength = 4000
snippetLength = 100
absoluteURL = false

[params.page]
rssFullText = true
[params.page.share]
Line = false
Weibo = false
Linkedin = true

[params.page.code]
copy = true

[params.footer]
hugo = false
copyright = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  lineNumbersInTable = true
  # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
  noClasses = false

[params.page.comment]
  enable = true
  [params.page.comment.disqus]
    enable = true
    shortname = "blog-jayjanssen-net"
